[[plugins]] # Codic
repo = 'koron/codic-vim'
	on_cmd = 'Codic'

[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
	on_i = 1
	hook_source = '''
		let g:user_emmet_mode = 'i'
		let g:user_emmet_leader_key='<C-E>'
		let g:use_emmet_complete_tag = 1
		let g:user_emmet_settings = {
  		\   'variables': {
    	\       'lang': "ja"
      \   },
  		\   'indentation': '    '
    	\}
		'''

[[plugins]]
repo = 'rhysd/vim-clang-format'
	hook_add = '''
		let g:clang_format#style_options = {
            \ "AccessModifierOffset" : "-3",
            \ "AllowShortIfStatementsOnASingleLine" : "true",
            \ "AlwaysBreakTemplateDeclarations" : "true",
            \ "Standard" : "C++11",
            \ "IndentWidth": "4"}
		autocmd FileType c,cpp,objc nnoremap <buffer><Leader>cf :<C-u>ClangFormat<CR>
		autocmd FileType c,cpp,objc vnoremap <buffer><Leader>cf :ClangFormat<CR>
		autocmd FileType c,cpp,objc map <buffer><Leader>x <Plug>(operator-clang-format)
		nmap <Leader>C :ClangFormatAutoToggle<CR>
	'''

[[plugins]] # EditorConfig
repo = 'editorconfig/editorconfig-vim'
  on_path = '.*'
