# coding

[[plugins]] # markdown viewer
repo = 'iamcco/markdown-preview.vim'
on_ft = ['markdown', 'mkd']

[[plugins]] # 括弧
repo  = 'cohama/lexima.vim'

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
hook_source = '''
lua <<EOF
    local async = require "plenary.async"
EOF
'''

[[plugins]]
repo = 'nvim-lua/popup.nvim'

# fzf
[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'skanehira/k8s.vim'
