# coding

[[plugins]] # markdown viewer
repo = 'iamcco/markdown-preview.vim'
on_ft = ['markdown', 'mkd']

[[plugins]] # 括弧
repo  = 'cohama/lexima.vim'

[[plugins]]
repo = 'mattn/vim-maketable'

# fzf
[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  " Show hidden files
  let g:fern#default_hidden=1
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
