# coding

[[plugins]]  # markdown viewer
on_ft = ['markdown', 'mkd']
repo = 'iamcco/markdown-preview.vim'

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'skanehira/k8s.vim'

# DDC-related plugins - DISABLED for nvim-cmp migration
# [[plugins]]
# repo = 'Shougo/ddc-nvim-lsp.vim'
#
# [[plugins]]
# repo = 'shougo/ddc-ui-pum'
# on_source = 'ddc.vim'
#
# [[plugins]]
# repo = 'shougo/ddc-around'
# on_source = 'ddc.vim'
#
# [[plugins]]
# repo = 'LumaKernel/ddc-file'
# on_source = 'ddc.vim'
#
# [[plugins]]
# repo = 'shun/ddc-vim-lsp'
# on_source = 'ddc.vim'
#
# [[plugins]]
# repo = 'tani/ddc-fuzzy'
# on_source = 'ddc.vim'
