# status

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]] # status line
repo = 'itchyny/lightline.vim'
hook_add = '''
        let g:lightline = { 
        \ 'active': {
        \  'left':  [ [ 'mode', 'paste'],
        \             [ 'readonly', 'filename', 'modified', 'gitbranch' ] ],
        \  'right': [ [ 'percent' ],
        \             [ 'lineinfo' ],
        \             [ 'fileencoding', 'fileformat', 'filetype' ] ]
        \ },
        \ 'component_function': {
        \   'gitbranch': 'FugitiveHead'
        \ },
        \ 'colorscheme': 'wombat',
        \ 'separator': { 'left': "", 'right': "" },
        \ 'subseparator': { 'left': "", 'right': "" }
        \}
'''


# Lang

# [[plugins]] # Haml
# repo  = 'tpope/vim-haml'
# on_ft = 'haml'
# 
# [[plugins]] # Html5
# repo  = 'othree/html5.vim'
# on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
        let g:vim_markdown_frontmatter = 1
        let g:vim_markdown_math = 1
'''

[[plugins]] # Terraform
repo = 'hashivim/vim-terraform'
on_ft = ['tf', 'terraform', 'hcl']
hook_add = '''
        let g:terraform_fmt_on_save = 1
'''

# [[plugins]] # c, cpp
# repo = 'arakashic/chromatica.nvim'
# on_ft = ['c', 'cpp', 'cmake']
# hook_add = '''
# 	let g:chromatica#libclang_path='/opt/local/libexec/llvm-5.0/lib'
# 	let g:chromatica#enable_at_startup=1
# '''

# git
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
	let updatetime = 250
        nmap <C-g>g :GitGutterToggle<CR>
        nmap <C-g>h :GitGutterLineHighlightsToggle<CR>
'''

[[plugins]]
repo = 'tpope/vim-fugitive'


# template
[[plugins]]
repo = 'thinca/vim-template'
hook_add = '''
        let g:template_basedir = '~/.config'
        let g:template_free_pattern = 'template'
        " テンプレート中に含まれる文字を置き換える
        au MyAutoCmd User plugin-template-loaded call s:template_keywords()
        function! s:template_keywords()
            silent! %s/<+DATE+>/\=strftime('%Y-%m-%d %T %z')/g
            silent! %s/<+FILENAME+>/\=expand('%:r')/g
        endfunction
        " テンプレート中に含まれる'<+CURSOR+>'にカーソルを移動
        au MyAutoCmd User plugin-template-loaded
            \   if search('<+CURSOR+>')
            \ |   silent! execute 'normal! "_da>'
            \ | endif
'''

# colorscheme

# [[plugins]] # hybrid
# repo = 'w0ng/vim-hybrid'

# [[plugins]] # solarized
# repo = 'altercation/vim-colors-solarized'

[[plugins]] # badwolf
repo = 'sjl/badwolf'

# [[plugins]] # cobalt
# repo = 'gkjgh/cobalt'

# [[plugins]] # monokai
# repo = 'tanvirtin/monokai.nvim'

# colorscheme指定
hook_add = '''
	set background=dark
	" colorscheme 設定は source 後に行う必要があるので確実に読まれている VimEnter のタイミングで行う。
	" 但し Colorscheme イベントの発生が抑制されないよう nested を付ける。
        au MyAutoCmd VimEnter * nested colorscheme badwolf
'''

# 補完

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_source = '''
        " debug
        let g:lsp_log_verbose = 1
        let g:lsp_log_file = expand('~/.cache/dein/vim-lsp.log')

        let g:lsp_signs_error = '⨉'
        let g:lsp_signs_warning = '⚠'
        if executable('pyls')
            au User lsp_setup call lsp#register_server({
                \ 'name': 'pyls',
                \ 'cmd': {server_info->['pyls']},
                \ 'whitelist': ['python'],
                \ })
        endif

        if executable('clangd')
            au User lsp_setup call lsp#register_server({
                \ 'name': 'clangd',
                \ 'cmd': {server_info->['clangd', '-background-index']},
                \ 'whitelist': ['c', 'cpp'],
                \ })
        endif

        function! s:configure_lsp() abort
          setlocal omnifunc=lsp#complete   " オムニ補完を有効化
        endfunction
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

# [[plugins]]
# repo = 'neovim/nvim-lspconfig'

# nvim-treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
hook_add = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
  },
  indent = {
    enable = true
  },
  rainbow = {
    enable = true,
    extended_mode = true,
    max_file_lines = nil,
  }
}
EOF
'''

[[plugins]]
repo = 'romgrk/nvim-treesitter-context'
