[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = { 
  \   'colorscheme': 'wombat'
  \}
'''

# Lang

  [[plugins]] # Haml
  repo  = 'tpope/vim-haml'
  on_ft = 'haml'

  [[plugins]] # Html5
  repo  = 'othree/html5.vim'
  on_ft = 'html'

  [[plugins]] # Toml
  repo  = 'cespare/vim-toml'
  on_ft = 'toml'

  [[plugins]] # Markdown
  repo = 'rcmdnk/vim-markdown'
  on_ft = ['markdown','mkd']
  hook_add = '''
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_math = 1
  '''

  [[plugins]] # Japanese doc
  repo = 'vim-jp/vimdoc-ja'
  on_ft = 'help'
  hook_add = '''
    set helplang=ja,en
  '''


# 補完

	[[plugins]] 
	repo = 'Shougo/deoplete.nvim'
	if = 'has("python3")'
	depends = 'context_filetype.vim'
	on_event = 'IntertCharPre'
	hook_add = '''
		let g:deoplete#enable_at_startup = 1
  	let g:deoplete#auto_complete_delay = 0
  	let g:deoplete#auto_complete_start_length = 1
  	let g:deoplete#enable_camel_case = 0
  	let g:deoplete#enable_ignore_case = 0
  	let g:deoplete#enable_refresh_always = 0
  	let g:deoplete#enable_smart_case = 1
  	let g:deoplete#file#enable_buffer_path = 1
  	let g:deoplete#max_list = 10000
	'''
	on_i = 1

	[[plugins]] #python
	repo = 'zchee/deoplete-jedi'
	depends = 'Shougo/deoplete.nvim'


[[plugins]] # python indent
repo = 'tell-k/vim-autopep8'
hook_add = '''
let g:autopep8_disable_show_diff = 1
'''


# Colors

[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'

[[plugins]] # badwolf
repo = 'sjl/badwolf'

[[plugins]] # cobalt
repo = 'gkjgh/cobalt'

# colorscheme指定
hook_add = '''
	set background=dark
	" colorscheme 設定は source 後に行う必要があるので確実に読まれている VimEnter のタイミングで行う。
	" 但し Colorscheme イベントの発生が抑制されないよう nested を付ける。
   au MyAutoCmd VimEnter * nested colorscheme badwolf
'''
