[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = { 
  \   'colorscheme': 'wombat'
    \}
'''

# 括弧補完
  [[plugins]] 
  repo  = 'cohama/lexima.vim'

# Lang

  [[plugins]] # C,C++
	repo = 'arakashic/chromatica.nvim'
		hook_add = '''
			let g:chromatica#libclang_path='/opt/local/libexec/llvm-5.0/lib'
			let g:chromatica#enable_at_startup=1
		'''

  [[plugins]] # Haml
  repo  = 'tpope/vim-haml'
    on_ft = 'haml'

  [[plugins]] # Html5
  repo  = 'othree/html5.vim'
    on_ft = 'html'

  [[plugins]] # Toml
  repo  = 'cespare/vim-toml'
    on_ft = 'toml'

  [[plugins]] # Markdown
  repo = 'rcmdnk/vim-markdown'
    on_ft = ['markdown','mkd']
    hook_add = '''
      let g:vim_markdown_frontmatter = 1
      let g:vim_markdown_math = 1
    '''

  [[plugins]] # Japanese doc
  repo = 'vim-jp/vimdoc-ja'
    on_ft = 'help'
    hook_add = '''
      set helplang=ja,en
    '''

# Colors

  [[plugins]] # hybrid
  repo = 'w0ng/vim-hybrid'

  [[plugins]] # solarized
  repo = 'altercation/vim-colors-solarized'

  [[plugins]] # badwolf
  repo = 'sjl/badwolf'

  [[plugins]] # cobalt
  repo = 'gkjgh/cobalt'
	
	# colorscheme指定
	hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので確実に読まれている VimEnter のタイミングで行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme badwolf
	'''
